INSERT INTO public.planners (
  business_name,
  description,
  location_city,
  location_state,
  email,
  website_url,
  instagram_handle,
  is_verified,
  category,
  specialties,
  services,
  years_experience,
  base_price,
  average_rating,
  total_reviews
) VALUES 
(
  'Inspired Event Co',
  'Professional event planning and coordination services led by Alex Nolan, creating inspired celebrations and memorable experiences.',
  'Wellington',
  'Wellington',
  'alex@inspiredeventco.co.nz',
  'https://inspiredeventco.co.nz',
  'inspiredeventco',
  true,
  '{"Wedding Planning", "Corporate Events"}',
  '{"Full Service Planning", "Day of Coordination", "Corporate Events"}',
  '{"Event Planning", "Venue Selection", "Vendor Coordination", "Timeline Management"}',
  8,
  3500.00,
  4.8,
  12
),
(
  'Oh! Such Style',
  'Stylish event planning and design services by Danielle and team, specializing in beautifully curated celebrations with impeccable attention to detail.',
  'Auckland',
  'Auckland',
  'danielle@ohsuchstyle.co.nz',
  'https://ohsuchstyle.co.nz',
  'ohsuchstyle',
  true,
  '{"Wedding Planning", "Event Styling"}',
  '{"Wedding Styling", "Event Design", "Luxury Events"}',
  '{"Event Styling", "Floral Design", "Venue Decoration", "Theme Development"}',
  10,
  4200.00,
  4.9,
  18
),
(
  'I Do For You',
  'Comprehensive wedding planning services by Moira Murphy, dedicated to making your special day perfect with personalized attention and expert coordination.',
  'Christchurch',
  'Canterbury',
  'moira@idoforyou.co.nz',
  'https://www.idoforyou.co.nz',
  'idoforyouweddings',
  true,
  '{"Wedding Planning"}',
  '{"Wedding Planning", "Bridal Services", "Ceremony Coordination"}',
  '{"Full Wedding Planning", "Partial Planning", "Day of Coordination", "Vendor Management"}',
  12,
  3800.00,
  4.7,
  15
),
(
  'Nicholls & Co - Wedding & Events',
  'Premium wedding and event planning services covering Dunedin and Otago region, creating exceptional celebrations with professional expertise.',
  'Dunedin',
  'Otago',
  'team@nichollsandco.com',
  'https://www.nichollsandco.com',
  'nichollsandco.nz',
  true,
  '{"Wedding Planning", "Corporate Events"}',
  '{"Luxury Weddings", "Destination Events", "Corporate Functions"}',
  '{"Event Planning", "Wedding Coordination", "Venue Management", "Catering Coordination"}',
  15,
  4500.00,
  4.8,
  22
);