// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijcxgimuotmllyewptce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqY3hnaW11b3RtbGx5ZXdwdGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTY3NzYsImV4cCI6MjA2OTc5Mjc3Nn0.bita5P0P0Nu9li9ZHNTrzkFwX4Y4Mk9CtRnSCEtj6hc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});